create table users (
        id bigint generated by default as identity,
        created timestamp(6),
        email varchar(255),
        isactive boolean not null,
        last_login timestamp(6),
        modified timestamp(6),
        name varchar(255),
        password varchar(255) not null,
        token uuid,
        primary key (id)
    )
	
	
	  create table phones (
        id_phone bigint generated by default as identity,
        citycode varchar(255),
        countrycode varchar(255),
        number varchar(255),
        user_id bigint,
        primary key (id_phone)
    )
	
 alter table if exists users 
       drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7
	   
    alter table if exists users 
       add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email)
	   
alter table if exists phones 
       add constraint FKmg6d77tgqfen7n1g763nvsqe3 
       foreign key (user_id) 
       references users